Electrolyzer model
Cislunar-Explorers/CislunarSim pull request #48
Opened 2022-11-01 06:18 UTC by cameron-goddard

### Summary

Implemented the electrolyzer model according to what we know about the electrolyzer setup on the spacecraft right now. There might be some changes later on depending on whether or not we will have two combustion chambers etc.

### Testing
Added some basic unit tests

### Notes
N/A

### Comments
- [x] Add an x between the brackets if you commented your code well!

2022-11-01 07:42 UTC, andrew032011 commented
As a hint for why the tests are failing, you updated the `Parameters` and `State` classes, but there are tests in `state_test.py` and `parameters_test.py` that need to be updated alongside that change, or else they will fail. In particular, if we look at the logs, `test_to_array()` in `state_test.py` simply checks that a State is being properly converted into an array, but our test case for a state_list is a list that doesn't incorporate the newly added fields for the State which you added, and neither does state_1 (from `test_utils.py`), so what happens is the fields of `state_1` are being set to their default values, and the test cases fails. 

Basically, you need to make some updates to `state_test.py`, `test_utils.py`, and `parameters_test.py` in order to "redefine" what the definition of a valid state/state-list and valid parameters are.

2022-11-05 16:23 UTC, adamrnasir requested changes
Looks pretty good; just a couple items that need to be addressed that I added comments for. Additionally, it's currently not passing pytest because of tests that verify state fields— I think the addition of new fields needs to be reflected in those tests.

For the sake of consistency and traceability, I'll PR `event_based` first then we can PR this on top of that.

2022-11-05 16:23 UTC, adamrnasir commented on src/core/models/electrolyzer_model.py
> +      print("duration:", self._duration)
Let's use logging rather than printing

2022-11-05 16:23 UTC, adamrnasir commented on tests/core_tests/model_tests/electrolyzer_model_test.py
> +        print(eval_a)
May want to remove this print statement for final version

2022-11-12 17:28 UTC, andrew032011 approved these changes

2022-11-12 17:41 UTC, adamrnasir approved these changes

2022-11-12 17:42 UTC, merged