Gyro model
Cislunar-Explorers/CislunarSim pull request #9
Opened 2022-03-23 22:45 UTC by cameron-goddard

### Summary

This PR addresses Jira ticket [CISLUNAR-165](https://jira.cornell.edu/browse/CISLUNAR-165).

`parameters.py` was updated with the gyro bias and gyro noise values. A new file `gyro_model.py` was created to implement the model as a subclass of `SensorModel`.

### Testing

Testing is not possible yet, as it is dependent on `state.py` being functional

### Notes

[Gyro Sensor Model](https://cornell.app.box.com/folder/158750635578)

### Comments
- [x] Add an x between the brackets if you commented your code well!

2022-03-23 23:15 UTC, tmf97 requested changes
Solid stuff, only small changes

2022-03-23 23:15 UTC, tmf97 commented on src/core/parameters.py
> +        self.gyro_bias = [0.497625, -0.10821875, 0.77490625] #truncate to same # of decimal places?
Don't worry, no need to truncate decimal places

2022-03-23 23:15 UTC, tmf97 commented on src/core/models/gyro_model.py
> +        return {"ang_vel.x": ang_vel_d[0], "ang_vel.y": ang_vel_d[1], "ang_vel.z": ang_vel_d[2]} #return as quaternion rate?
No need to convert to quaternion rates here. The gyro sensor spits out only angular velocity rates in x/y/z, so this is good.

2022-03-23 23:15 UTC, tmf97 commented on src/core/models/gyro_model.py
> +    def d_state(self, state: State) -> Dict[str, Any]:
We'll probably want to change the `SensorModel` base class a little bit, but that's for a future PR

2022-03-23 23:15 UTC, tmf97 commented on src/core/state.py
> +}
Solid start, but let's get on state.py in a new PR

2022-03-23 23:15 UTC, tmf97 commented on src/core/models/gyro_model.py
> +    """The gyro sensor model. This model applies the gyro bias and noise as specified in parameters.py"""
Can we add the box link to the doc you made for this?

2022-03-23 23:15 UTC, tmf97 commented on src/core/models/gyro_model.py
> +        return {"ang_vel.x": ang_vel_d[0], "ang_vel.y": ang_vel_d[1], "ang_vel.z": ang_vel_d[2]} #return as quaternion rate?
The _one_ small thing that's missing here is the quantization of the gyro rates. A perfect `float` is much more precise than values the gyro sensor is able to return. So after adding the noise, snap the value to the closest value allowed by the precision of the gyroscope

2022-03-25 21:36 UTC, tmf97 requested changes

2022-03-25 21:36 UTC, tmf97 commented on src/core/models/gyro_model.py
> +        return {"ang_vel.x": ang_vel_d[0], "ang_vel.y": ang_vel_d[1], "ang_vel.z": ang_vel_d[2]}
We'll probably want to change the type that this function returns, but OK for now

2022-03-25 21:36 UTC, tmf97 commented on src/core/parameters.py
> +        self.gyro_sensitivity = 0.15625
please make sure your units are consistent

2022-03-25 21:49 UTC, tmf97 approved these changes

2022-03-25 22:35 UTC, sjz38 commented on src/core/models/gyro_model.py
> +    def d_state(self, state: State) -> Dict[str, Any]:
Add docstring for return values

2022-03-26 20:35 UTC, tmf97 approved these changes

2022-03-26 20:35 UTC, merged